[package]
name = "points_on_curve"
version = "0.7.0"
edition = "2021"
authors = ["Orhan Balci <orhanbalci@gmail.com>", "VexyArt <vexyart@proton.me>"]
description = "Calculate points along Bezier curves"
repository = "https://github.com/vexyart/vruffr"
homepage = "https://github.com/vexyart/vruffr"
keywords = ["graphics", "bezier", "curves"]
categories = ["graphics", "algorithms"]
license = "MIT"
readme = "README.md"
rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22"
num-traits = "0.2"

[dev-dependencies]
piet-common = {version = "0.6", features = ["png"]}
piet = "0.6"
